/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.master;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tricky-Laptop
 */
public class dataTenant extends javax.swing.JInternalFrame {

    /**
     * Creates new form dataTenant
     */
    public dataTenant() {
        initComponents();
        tampilkanData();
        // Mengambil UI dari JInternalFrame
        javax.swing.plaf.basic.BasicInternalFrameUI ui = (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        javax.swing.JComponent northPane = ui.getNorthPane();

        // Menghapus semua listener mouse pada title bar agar tidak bisa digeser
        if (northPane != null) {
            for (java.awt.event.MouseListener listener : northPane.getMouseListeners()) {
            northPane.removeMouseListener(listener);
            }
        for (java.awt.event.MouseMotionListener listener : northPane.getMouseMotionListeners()) {
            northPane.removeMouseMotionListener(listener);
            }
        }
    }
    
    public void tampilkanData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Email");
        model.addColumn("No. Handphone");
        model.addColumn("No. Kamar");
        model.addColumn("Tanggal Masuk");
        model.addColumn("Tenggat Bayar");
        model.addColumn("Harga/Bulan");
        
        try{
            Connection conn = aplikasikos.Connector.getKoneksi(); 
            Statement stmt = conn.createStatement();
            
            String query = "SELECT * FROM tblTenant ORDER BY id_tenant DESC";
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_tenant"),
                    rs.getString("nama_tenant"),
                    rs.getString("email"),
                    rs.getString("nomor_hp"),
                    rs.getString("nomor_kamar"),
                    rs.getString("tanggal_masuk"),
                    rs.getString("tenggat_bayar"),
                    rs.getInt("harga_bulan")
                });
            }
            tableDataTenant.setModel(model);
            tableDataTenant.getColumnModel().getColumn(0).setPreferredWidth(40);   // ID
            tableDataTenant.getColumnModel().getColumn(1).setPreferredWidth(180);  // Nama Tenant
            tableDataTenant.getColumnModel().getColumn(2).setPreferredWidth(140);  // Email
            tableDataTenant.getColumnModel().getColumn(3).setPreferredWidth(100);  // No. HP
            tableDataTenant.getColumnModel().getColumn(4).setPreferredWidth(80);   // No. Kamar
            tableDataTenant.getColumnModel().getColumn(5).setPreferredWidth(100);  // Tanggal Masuk
            tableDataTenant.getColumnModel().getColumn(6).setPreferredWidth(100);  // Tenggat Bayar
            tableDataTenant.getColumnModel().getColumn(7).setPreferredWidth(100);  // Harga/Bulan
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Gagal Memuat Data Tabel : " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataTenant = new javax.swing.JTable();

        setBackground(new java.awt.Color(141, 141, 141));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Data Tenant Aktif"));
        setForeground(java.awt.Color.cyan);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Data Dipilih");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Data Dipilih");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tableDataTenant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Tenant", "Email", "No. Handphone", "No. Kamar", "Tanggal Masuk", "Tenggat Bayar", "Harga/Bulan"
            }
        ));
        tableDataTenant.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tableDataTenant);
        if (tableDataTenant.getColumnModel().getColumnCount() > 0) {
            tableDataTenant.getColumnModel().getColumn(0).setResizable(false);
            tableDataTenant.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableDataTenant.getColumnModel().getColumn(1).setResizable(false);
            tableDataTenant.getColumnModel().getColumn(2).setResizable(false);
            tableDataTenant.getColumnModel().getColumn(3).setResizable(false);
            tableDataTenant.getColumnModel().getColumn(4).setResizable(false);
            tableDataTenant.getColumnModel().getColumn(5).setResizable(false);
            tableDataTenant.getColumnModel().getColumn(6).setResizable(false);
            tableDataTenant.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int baris = tableDataTenant.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data tenant di tabel yang ingin di-edit!");
            return;
        }

        // 1. Ambil data dari baris tabel yang dipilih
        String id = tableDataTenant.getValueAt(baris, 0).toString();
        String nama = tableDataTenant.getValueAt(baris, 1).toString();
        String email = tableDataTenant.getValueAt(baris, 2).toString() != null ? tableDataTenant.getValueAt(baris, 2).toString() : "";
        String hp = tableDataTenant.getValueAt(baris, 3).toString();
        String kamar = tableDataTenant.getValueAt(baris, 4).toString();
        String tanggal = tableDataTenant.getValueAt(baris, 5).toString(); 

        // 2. Panggil tambahTenant dengan constructor khusus EDIT
        tambahTenant formEdit = new tambahTenant(id, nama, email, hp, kamar, tanggal);

        // 3. Tampilkan ke JDesktopPane utama kamu
        getParent().add(formEdit);
        formEdit.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        tampilkanData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int barisTerpilih = tableDataTenant.getSelectedRow();
    
        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih salah satu data pada tabel yang ingin dihapus terlebih dahulu!");
            return;
        }
        String idTenant = tableDataTenant.getValueAt(barisTerpilih, 0).toString();
        String namaTenant = tableDataTenant.getValueAt(barisTerpilih, 1).toString();
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data tenant dengan nama '" + namaTenant + "'?", 
            "Konfirmasi Hapus Data", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        
        if(konfirmasi == javax.swing.JOptionPane.YES_OPTION){
            java.sql.Connection conn = null;
            java.sql.PreparedStatement psDelete = null;
            try {
                conn = aplikasikos.Connector.getKoneksi();
            
                // Query SQL untuk menghapus data berdasarkan ID primary key
                String queryDelete = "DELETE FROM tblTenant WHERE id_tenant = ?"; 
                psDelete = conn.prepareStatement(queryDelete);
            
                psDelete.setString(1, idTenant);

                int hasil = psDelete.executeUpdate();
                if (hasil > 0){
                    javax.swing.JOptionPane.showMessageDialog(this, "Data Tenant Berhasil Dihapus dari Database!");
                    btnRefreshActionPerformed(null);
                }
            }catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
            }finally{
                try{ 
                    if (psDelete != null) psDelete.close(); 
                }catch(Exception e) {}
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDataTenant;
    // End of variables declaration//GEN-END:variables
}
