/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.master;

/**
 *
 * @author Tricky-Laptop
 */
public class dataTenant extends javax.swing.JInternalFrame {

    /**
     * Creates new form dataTenant
     */
    public dataTenant() {
        initComponents();
        // Mengambil UI dari JInternalFrame
        javax.swing.plaf.basic.BasicInternalFrameUI ui = (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        javax.swing.JComponent northPane = ui.getNorthPane();

        // Menghapus semua listener mouse pada title bar agar tidak bisa digeser
        if (northPane != null) {
            for (java.awt.event.MouseListener listener : northPane.getMouseListeners()) {
            northPane.removeMouseListener(listener);
            }
        for (java.awt.event.MouseMotionListener listener : northPane.getMouseMotionListeners()) {
            northPane.removeMouseMotionListener(listener);
            }
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Data Tenant Aktif"));
        setForeground(java.awt.Color.cyan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
