/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.master;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Tricky-Laptop
 */
public class tambahTenant extends javax.swing.JInternalFrame {

    /**
     * Creates new form formTambahTenant
     */
    
    private String idTenantEdit = "";
    
    public tambahTenant() {
        initComponents();
        // Mengambil UI dari JInternalFrame
        javax.swing.plaf.basic.BasicInternalFrameUI ui = (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        javax.swing.JComponent northPane = ui.getNorthPane();

        // Menghapus semua listener mouse pada title bar agar tidak bisa digeser
        if (northPane != null) {
            for (java.awt.event.MouseListener listener : northPane.getMouseListeners()) {
            northPane.removeMouseListener(listener);
            }
        for (java.awt.event.MouseMotionListener listener : northPane.getMouseMotionListeners()) {
            northPane.removeMouseMotionListener(listener);
            }
        }
    }
    
    // Constructor BARU (untuk EDIT data)
    public tambahTenant(String id, String nama, String email, String hp, String kamar, String tanggal) {
        initComponents();
        
        // 1. Simpan ID ke variabel global agar bisa dipakai saat query UPDATE nanti
        this.idTenantEdit = id;
        
        // 2. Ubah judul Form dan teks Tombol agar menyesuaikan mode Edit
        this.setTitle("Edit Data Tenant - ID: " + id);
        btnSimpan.setText("Update Data"); 
        
        // 3. Set nilai komponen GUI sesuai data yang dipilih dari tabel
        txtNama.setText(nama);
        txtEmail.setText(email);
        txtHandphone.setText(hp);
        cmbKamar.setSelectedItem(kamar);
        txtTanggal.setText(tanggal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNama = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblKamar = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JFormattedTextField();
        cmbKamar = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblHandphone = new javax.swing.JLabel();
        txtHandphone = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah Tenant Baru"));

        lblNama.setText("Nama Tenant ");

        lblTanggal.setText("Tanggal Masuk");

        lblKamar.setText("Nomor Kamar ");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtTanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd MMMM yyyy"))));
        txtTanggal.setToolTipText("Ex : 01 January 2001");

        cmbKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==: Pilih Kamar :==", "Kamar 001", "Kamar 002", "Kamar 003", "Kamar 004", "Kamar 005", "Kamar 006", "Kamar 007", "Kamar 008", "Kamar 009", "Kamar 010", "Kamar 011" }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblEmail.setText("Email");

        lblHandphone.setText("No. Handphone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama)
                    .addComponent(lblKamar)
                    .addComponent(btnSimpan)
                    .addComponent(lblEmail)
                    .addComponent(lblHandphone)
                    .addComponent(lblTanggal))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNama)
                        .addComponent(cmbKamar, 0, 226, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEmail)
                        .addComponent(txtHandphone)))
                .addContainerGap(455, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHandphone)
                    .addComponent(txtHandphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKamar)
                    .addComponent(cmbKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnReset))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtEmail.setText("");
        txtHandphone.setText("");
        txtTanggal.setText("");
        cmbKamar.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(txtNama.getText().trim().isEmpty() || txtHandphone.getText().trim().isEmpty() || 
        txtTanggal.getText().trim().isEmpty() || cmbKamar.getSelectedIndex() == 0){
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field (kecuali email) wajib diisi dan kamar harus dipilih!");
            return;
        }
        
        String nama = txtNama.getText();
        String email = txtEmail.getText();
        String noHp = txtHandphone.getText();
        String noKamar = cmbKamar.getSelectedItem().toString();
        String tglMasuk = txtTanggal.getText(); // Hasil dari form: contoh "05 June 2026" atau "05 Juni 2026"
        
        String tglMasukSQL = "";
        String tglTenggatSQL = "";
        try {
            // 1. Definisikan formatter yang mengenali teks nama bulan Indonesia & Inggris
            java.time.format.DateTimeFormatter formatTeksIndo = java.time.format.DateTimeFormatter.ofPattern("dd MMMM yyyy", new java.util.Locale("id", "ID"));
            java.time.format.DateTimeFormatter formatTeksEng = java.time.format.DateTimeFormatter.ofPattern("dd MMMM yyyy", java.util.Locale.ENGLISH);
            
            java.time.LocalDate tanggalMasukObj;
            
            // 2. Coba parse menggunakan standar bahasa Indonesia dulu, jika gagal coba bahasa Inggris
            try {
                tanggalMasukObj = java.time.LocalDate.parse(tglMasuk, formatTeksIndo);
            } catch (Exception ex) {
                tanggalMasukObj = java.time.LocalDate.parse(tglMasuk, formatTeksEng);
            }
            
            // 3. Hitung tanggal tenggat otomatis +30 hari
            java.time.LocalDate tanggalTenggatObj = tanggalMasukObj.plusDays(30);
            
            // 4. Ubah ke format standar database MySQL (yyyy-MM-dd)
            tglMasukSQL = tanggalMasukObj.toString();
            tglTenggatSQL = tanggalTenggatObj.toString();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Format tanggal salah! Gunakan format teks (Contoh: 05 Juni 2026 atau 05 June 2026)");
            return;
        }
        
        java.sql.Connection conn = null;
        java.sql.PreparedStatement psCariHarga = null;
        java.sql.PreparedStatement psExecute = null;
        java.sql.ResultSet rs = null;
        
        try{
            int hargaBulan = 0;
            conn = aplikasikos.Connector.getKoneksi();
            
            String queryHarga = "SELECT harga_per_bulan FROM tblkamar WHERE nomor_kamar = ?";
            psCariHarga = conn.prepareStatement(queryHarga);
            psCariHarga.setString(1, noKamar);
            rs = psCariHarga.executeQuery();
            
            if (rs.next()) {
                hargaBulan = rs.getInt("harga_per_bulan"); // Mengisi variabel global blok try
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Data kamar tidak ditemukan di database!");
                return;
            }
            if (idTenantEdit.equals("")){
            String queryInsert = "INSERT INTO tbltenant (nama_tenant, email, nomor_hp, nomor_kamar, tanggal_masuk, tenggat_bayar, harga_bulan) VALUES (?, ?, ?, ?, ?, ?, ?)";
            psExecute = conn.prepareStatement(queryInsert);
        
            psExecute.setString(1, nama);
            psExecute.setString(2, email);
            psExecute.setString(3, noHp);
            psExecute.setString(4, noKamar);
            psExecute.setString(5, tglMasukSQL);
            psExecute.setString(6, tglTenggatSQL); 
            psExecute.setInt(7, hargaBulan);
            } else {
                String queryUpdate = "UPDATE tblTenant SET nama_tenant=?, email=?, nomor_hp=?, nomor_kamar=?, tanggal_masuk=?, tenggat_bayar=?, harga_bulan=? WHERE id_tenant=?";
                psExecute = conn.prepareStatement(queryUpdate);
        
                psExecute.setString(1, nama);
                psExecute.setString(2, email);
                psExecute.setString(3, noHp);
                psExecute.setString(4, noKamar);
                psExecute.setString(5, tglMasukSQL);
                psExecute.setString(6, tglTenggatSQL); 
                psExecute.setInt(7, hargaBulan);
                psExecute.setString(8, idTenantEdit);
            }
            int hasil = psExecute.executeUpdate();
            if (hasil > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Tenant Berhasil Disimpan!");
            
                txtNama.setText("");
                txtEmail.setText("");
                txtHandphone.setText("");
                txtTanggal.setText("");
                cmbKamar.setSelectedIndex(0);
            }
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }finally{
            // Menutup semua resource database
            try { if (rs != null) rs.close(); } catch (Exception e) {}
            try { if (psCariHarga != null) psCariHarga.close(); } catch (Exception e) {}
            try { if (psExecute != null) psExecute.close(); } catch (Exception e) {}
        }
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKamar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHandphone;
    private javax.swing.JLabel lblKamar;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHandphone;
    private javax.swing.JTextField txtNama;
    private javax.swing.JFormattedTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
