/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.master.dataTenant;
import view.master.tambahTenant;

/**
 *
 * @author Tricky-Laptop
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrameUtama
     */
    public frameUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAplikasi = new javax.swing.JMenu();
        submenuCloseApp = new javax.swing.JMenuItem();
        submenuClose = new javax.swing.JMenuItem();
        menuData = new javax.swing.JMenu();
        submenuDataTenant = new javax.swing.JMenuItem();
        submenuTambahData = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(95, 95, 95));

        container.setBackground(new java.awt.Color(95, 95, 95));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang, Gunakan menu Data untuk memulai");

        container.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        menuAplikasi.setText("Aplikasi");

        submenuCloseApp.setText("Tutup Aplikasi");
        submenuCloseApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCloseAppActionPerformed(evt);
            }
        });
        menuAplikasi.add(submenuCloseApp);

        submenuClose.setText("Tutup Jendela");
        submenuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCloseActionPerformed(evt);
            }
        });
        menuAplikasi.add(submenuClose);

        jMenuBar1.add(menuAplikasi);

        menuData.setText("Data");
        menuData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataActionPerformed(evt);
            }
        });

        submenuDataTenant.setText("Data Tenant");
        submenuDataTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuDataTenantActionPerformed(evt);
            }
        });
        menuData.add(submenuDataTenant);

        submenuTambahData.setText("Tambah Tenant");
        submenuTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuTambahDataActionPerformed(evt);
            }
        });
        menuData.add(submenuTambahData);

        jMenuBar1.add(menuData);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private dataTenant DataTenant = null;
    private tambahTenant TambahData = null;
    private void submenuDataTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuDataTenantActionPerformed
        if (TambahData != null){
            TambahData.dispose();
            TambahData = null;
        }
        if (DataTenant == null){
            DataTenant = new dataTenant();
            container.add(DataTenant);
            DataTenant.setVisible(true);
        }else{
            DataTenant.toFront();
        }
    }//GEN-LAST:event_submenuDataTenantActionPerformed

    private void submenuCloseAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCloseAppActionPerformed
        dispose();
    }//GEN-LAST:event_submenuCloseAppActionPerformed

    private void submenuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCloseActionPerformed
        if (DataTenant != null){
            DataTenant.dispose();
        }
        if (TambahData !=null){
            TambahData.dispose();
        }
    }//GEN-LAST:event_submenuCloseActionPerformed

    private void menuDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataActionPerformed
        
    }//GEN-LAST:event_menuDataActionPerformed

    private void submenuTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuTambahDataActionPerformed
        if (DataTenant != null){
            DataTenant.dispose();
            DataTenant = null;
        }
        if (TambahData == null){
            TambahData = new tambahTenant();
            container.add(TambahData);
            TambahData.setVisible(true);
        }else{
            TambahData.toFront();
        }
    }//GEN-LAST:event_submenuTambahDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAplikasi;
    private javax.swing.JMenu menuData;
    private javax.swing.JMenuItem submenuClose;
    private javax.swing.JMenuItem submenuCloseApp;
    private javax.swing.JMenuItem submenuDataTenant;
    private javax.swing.JMenuItem submenuTambahData;
    // End of variables declaration//GEN-END:variables
}
